### ISSUE TITLE
Editor doesn't show error on forgotten $ to define parameter

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#15]
The WOOL Editor does not show an error on statements like this:

`<<if someVariable == false >>`

The variable "someVariable" should have been declared with "$someVariable". The "Run" function of the Editor breaks on this.

**Comment by borisvanschooten** [comment]
Variables not preceded by '$' are now flagged with an error.

**Comment by borisvanschooten** [comment]
Oh, and  I found that by "break" you mean that the dialogue engine generates an uncaught runtime error.  Such runtime errors are now caught and displayed.
