### ISSUE TITLE
Editor falsely report an error on <<action .. >> tag

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#17]
The editor shows an error: cannot parse action on the following reply statement, while this is a valid reply option with an action:

`[[Show me my activity.|DiscussProgress|<<action type="generic" value="OPEN_ACTIVITY_BOOK">>]]`

**Comment by borisvanschooten** [comment]
<<Action>> was not implemented yet, I now implemented action parsing. The dialogue shows an alert when an action is supposed to be executed.
