### ISSUE TITLE
Editor doesn't draw node-pointer arrows that are located inside conditionals

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#18]
In the following example node, the [[NodeCats]] and [[NodeDogs]] don't seem to be recognized as node-pointers. If there is no node called "NodeCats", no error/warning is generated, and when the node does exist, no arrows are drawn.

```
<<if $someVariable == true>>
    Okay, since that is true, let's talk about cats.
    [[NodeCats]]    
<<else>>
    Hmm, since that is not true, let's talk about dogs.
    [[NodeDogs]]
<<endif>>
```

**Comment by borisvanschooten** [comment]
Arrows are already drawn to NodeCats/Dogs, although no error was generated.  Link parsing was improved which also generates errors for this case.
