### ISSUE TITLE
JavaScript parser falsely complains about String comparisons

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#24]
The WOOL editor complains about the following string comparison statement (that should be correct in my opinion).

`<<if $thisIsAString == "Some string." >>`

The editor says: "error: Variable 'string' missing '$' prefix" (see screenshot).

<img width="1369" alt="Screenshot 2019-10-17 at 15 38 13" src="https://user-images.githubusercontent.com/11227304/67014168-a60bfa00-f0f4-11e9-8ad0-61159bb58d80.png">

**Comment by hopdenakker** [comment]
Related, the parser also complains about number comparisons (see screenshot below)...

<img width="1345" alt="Screenshot 2019-10-17 at 15 45 38" src="https://user-images.githubusercontent.com/11227304/67014477-35191200-f0f5-11e9-8019-5a6d33d183e6.png">

**Comment by hopdenakker** [comment]
See also "conditionals.wool" in the test-dialogues folder.

**Comment by borisvanschooten** [comment]
Fixed, though shallow parsing used is still not fully watertight.
