### ISSUE TITLE
Add "Speaker" to the 'tags' bar visualization in nodes

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#3]
When adding a tag to a node, this is visualized at the bottom of a Node (see screenshot). The speaker tag should be added here (always the first one displayed, and preferably in a different color to emphasize it).

![image](https://user-images.githubusercontent.com/11227304/59715715-c4c8b580-9214-11e9-93ed-ae7583d81df1.png)

**Comment by borisvanschooten** [comment]
Fixed.
