### ISSUE TITLE
WOOL Editor, when returning from "Run" mode, store location in file tree

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#37]
In the Electron version of the WOOL Editor, when testing a dialogue with the "Run" option, and then returning to the edit window, the "file list" is fully collapsed again.

It would be good to save the "state" of this file tree, and restore it upon returning to the editor.

**Comment by borisvanschooten** [comment]
The state of the tree (nodes open/closed) is now made persistent.
