### ISSUE TITLE
WOOL Editor - Export POEditor Terms Bug in Electron App

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#38]
In the Electron version of the WOOL Editor (on Mac): when selecting the EXPORT POEDITOR TERMS, a .json file is immediately stored next to the .wool file (this is fine for now, although it may be better to give users the option of storing these elsewhere). However, right after this, the app is trying to save a "file.csv", prompting for a file location. The file that it's trying to save is actually the index.html of the editor (very weird...)

**Comment by borisvanschooten** [comment]
The save file code was not suited for json files, hence the strange behaviour. I fixed it so that you get a regular save dialog.
