### ISSUE TITLE
WOOL Editor falsely complains about "null" check...

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#39]
The following is a correct WOOL statement to check for the variable not having been set (having no value):

`<<if $variable == null>>`

Currently, the WOOL Editor gives an error on such statement: "Error: variable 'null' missing '$' prefix" (which is incorrect).

**Comment by borisvanschooten** [comment]
The literal null is not supported by the client parser.  As it is, "==" has "falsey" semantics, meaning that a==null and a==false mean the same as !a. As is, it's not very meaningful to write a == null.

**Comment by borisvanschooten** [comment]
Null was not yet supported as a literal. Fixed.
