### ISSUE TITLE
WOOL Editor (Electron) - Right-click -> New Node (wrong position)

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#41]
When right clicking anywhere in the Editor, it is supposed to create a new node under the position of the mouse. In the Electron version however, the position at which the new node is created has a wrong offset (I have a feeling that it's adding the width of the sidebar, making it appear too far to the right).

**Comment by borisvanschooten** [comment]
Yes, it's the offset of the sidebar that caused this issue. Fixed.
