### ISSUE TITLE
WOOL Editor: Run Mode -> "Edit Node" leads to strangely behaving edit node field

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#42]
When test-running a WOOL script, and then selecting the "Edit Node" button to open the node-editor on the currently displayed node, this "editor" field is behaving very erratically... difficult to explain, but for example, putting the text-selector somewhere will have the whole editor window "shaking"...

**Comment by borisvanschooten** [comment]
Was width problem caused by timing issue. Fixed.
