### ISSUE TITLE
WOOL Editor: Error on <<action >> statements

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#43]
Editor Version: 1.4.0
Web or Desktop: Desktop
Operating System: Mac
Browser (for Web): -

The editor gives an error on the following statement:

`<<action type="generic" value="CLOSE_BOOK">>`

The error given is as follows:

`Error: cannot parse << ... >> statement`

But it's a correct WOOL action statement :)

**Comment by borisvanschooten** [comment]
Is this an <<action>> statement within a reply? Please give example code.

**Comment by hopdenakker** [comment]
It's a "separate" statement within a WOOL Node:

```
<<action type="generic" value="CLOSE_BOOK">>

So, let's close the book.

[[Okay.|NextNode]]
```

**Comment by borisvanschooten** [comment]
Ok, the JS parser currently does not support separate action statements. I'll add it.

**Comment by borisvanschooten** [comment]
Separate action statements are now supported.
