### ISSUE TITLE
WOOL Editor: Area selector offset bug

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#44]
-- Editor Version: 1.4.0
-- Web or Desktop: Desktop
-- Operating System: Mac
-- Browser (for Web): -

---- Describe the Issue: ----
When creating a "selection field" (i.e. hold down LMB and drag), the selection-area has an offset (related to the width of the side bar)

**Comment by borisvanschooten** [comment]
The bug was also in the mouse wheel zoom function. Fixed.
