### ISSUE TITLE
WOOL Editor: Typo in warning message 

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#45]
-- Editor Version: 1.4.0
-- Web or Desktop: Desktop
-- Operating System: Mac
-- Browser (for Web):

---- Describe the Issue: ----
A warning is given if a single `=` is used instead of `==` in an `<<if >>`-statement, but the warning contains a spelling error:

`warning: Assigment operator '=' found in <<if>> statement. Did you mean '=='?`

Should be "Assignment"

**Comment by borisvanschooten** [comment]
Fixed.
