### ISSUE TITLE
WOOL Editor: Erroneous warning for >= in if-statements

### ISSUE THREAD

**Issue by hopdenakker** [RoessinghResearch/wool#46]
-- Editor Version: 1.4.0
-- Web or Desktop: Desktop
-- Operating System: Mac
-- Browser (for Web):

---- Describe the Issue: ----
The editor falsely gives a warning when if-statements contain things like `>=`, for example:

`<<if $userAge >= 65>>`

Gives the following warning:

`warning: Assigment operator '=' found in <<if>> statement. Did you mean '=='?`

**Comment by borisvanschooten** [comment]
Fixed for >= and <=.
